apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fast-long
  namespace: argo-workflows
spec:

  retryStrategy:
    limit: "3"
    retryPolicy: OnFailure
    expression: 'lastRetry.message matches "pod deleted" || lastRetry.exitCode in [64, 137, 143]'
    backoff:
      duration: "1m"
      factor: "2"

  artifactRepositoryRef:
    key: cloudpipe-artifacts

  securityContext:
    runAsNonRoot: true

  templates:

  ##############################################
  # 1. Long Segmentation (seg_only --long)
  ##############################################

  - name: fastsurfer-long-segmentation-steps-template
    inputs:
      parameters:
        - name: T1w_sessions

    steps:
    - - name: fastsurfer-long-segmentation-step
        template: fastsurfer-long-segmentation-template
        arguments:
          parameters:
            - name: argstring
              value: >-
                {{= "--subjects " +
                   join(map(jsonpath(inputs.parameters.T1w_sessions, "$[*]"), {# + "=from-base"}), " ") +
                   " --sd /opt/freesurfer/subjects --seg_only --edits --fsaparc --long " +
                   workflow.parameters.subjID + "_template --threads 2" }}

  - name: fastsurfer-long-segmentation-template
    metadata:
      labels:
        cloudpipe.io/phase: anatomical
        cloudpipe.io/step: long-segmentation
    inputs:
      parameters:
        - name: argstring

    nodeSelector:
      karpenter.sh/nodepool: gpu-nodepool

    initContainers:
      - name: clear-is-running
        image: public.ecr.aws/docker/library/alpine:3.21
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            ephemeral-storage: 300M
        command: ["find", "/opt/freesurfer/subjects", "-name", "*IsRunning*", "-delete"]
        mirrorVolumeMounts: true

    container:
      image: "{{workflow.parameters.ecr-registry}}/cloudpipe/fastsurfer:sha-0aae28dd7e437306ca44f6081d4954737b03a056"
      imagePullPolicy: IfNotPresent

      volumeMounts:
      - name: "{{=lower(workflow.parameters.subjID)}}"
        mountPath: /opt/freesurfer/subjects
        subPath: opt/freesurfer/subjects

      resources:
        requests:
          memory: 8G
          cpu: '2'
        limits:
          nvidia.com/gpu: '1'

      command: [bash, -c]
      args: ["/fastsurfer/brun_fastsurfer.sh {{inputs.parameters.argstring}}"]

  ##############################################
  # 2. Long Parcellation (surf_only --long)
  ##############################################

  - name: fastsurfer-long-parcellation-steps-template
    inputs:
      parameters:
      - name: T1w_sessions

    steps:
    - - name: fastsurfer-long-parcellation-step
        template: fastsurfer-long-parcellation-template
        arguments:
          parameters:
            - name: argstring
              value: >-
                {{= "--subjects " +
                   join(map(jsonpath(inputs.parameters.T1w_sessions, "$[*]"), {# + "=from-base"}), " ") +
                   " --sd /opt/freesurfer/subjects --surf_only --fsaparc --edits --3T --long " +
                   workflow.parameters.subjID + "_template" +
                   " --parallel " + string(len(jsonpath(inputs.parameters.T1w_sessions, "$[*]"))) +
                   " --threads 4" }}
            - name: T1w_sessions
              value: '{{inputs.parameters.T1w_sessions}}'

  - name: fastsurfer-long-parcellation-template
    metadata:
      labels:
        cloudpipe.io/phase: anatomical
        cloudpipe.io/step: long-parcellation
    inputs:
      parameters:
        - name: argstring
        - name: T1w_sessions

      artifacts:
      - name: fslicense
        path: '/opt/freesurfer/.license'
        s3:
          endpoint: s3-accelerate.amazonaws.com
          bucket: "{{workflow.parameters.bucket}}"
          region: us-east-2
          key: 'config/fslicense'

    outputs:
      artifacts:
      - name: long-template-complete
        path: '/opt/freesurfer/subjects/{{workflow.parameters.subjID}}_template'
        s3:
          endpoint: s3-accelerate.amazonaws.com
          bucket: "{{workflow.parameters.bucket}}"
          region: us-east-2
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{workflow.parameters.subjID}}_long-template.tar.gz'

      - name: ses-00A-templated
        path: '/opt/freesurfer/subjects/ses-00A'
        s3:
          endpoint: s3-accelerate.amazonaws.com
          bucket: "{{workflow.parameters.bucket}}"
          region: us-east-2
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{workflow.parameters.subjID}}_ses-00A_templated.tar.gz'

      - name: ses-02A-templated
        path: '/opt/freesurfer/subjects/ses-02A'
        s3:
          endpoint: s3-accelerate.amazonaws.com
          bucket: "{{workflow.parameters.bucket}}"
          region: us-east-2
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{workflow.parameters.subjID}}_ses-02A_templated.tar.gz'
        optional: true

      - name: ses-04A-templated
        path: '/opt/freesurfer/subjects/ses-04A'
        s3:
          endpoint: s3-accelerate.amazonaws.com
          bucket: "{{workflow.parameters.bucket}}"
          region: us-east-2
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{workflow.parameters.subjID}}_ses-04A_templated.tar.gz'
        optional: true

      - name: ses-06A-templated
        path: '/opt/freesurfer/subjects/ses-06A'
        s3:
          endpoint: s3-accelerate.amazonaws.com
          bucket: "{{workflow.parameters.bucket}}"
          region: us-east-2
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{workflow.parameters.subjID}}_ses-06A_templated.tar.gz'
        optional: true

      - name: ses-08A-templated
        path: '/opt/freesurfer/subjects/ses-08A'
        s3:
          endpoint: s3-accelerate.amazonaws.com
          bucket: "{{workflow.parameters.bucket}}"
          region: us-east-2
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{workflow.parameters.subjID}}_ses-08A_templated.tar.gz'
        optional: true

      - name: ses-10A-templated
        path: '/opt/freesurfer/subjects/ses-10A'
        s3:
          endpoint: s3-accelerate.amazonaws.com
          bucket: "{{workflow.parameters.bucket}}"
          region: us-east-2
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{workflow.parameters.subjID}}_ses-10A_templated.tar.gz'
        optional: true

    # Set the number of CPUs requested to 4x the number of sessions, k; memory to 4k + 12 (GB; see also above under argstring)
    # In combination with the '--parallel' argument to FastSurfer, this should facilitate faster
    # concurrent parcellation of each session's data.
    podSpecPatch: |
      containers:
        - name: main
          resources:
            requests:
              cpu: '{{=len(jsonpath(inputs.parameters.T1w_sessions, "$[*]"))*4}}'
              memory: '{{=len(jsonpath(inputs.parameters.T1w_sessions, "$[*]"))*4 + 12}}G'

    nodeSelector:
      karpenter.sh/nodepool: cpu-heavy-nodepool

    initContainers:
      - name: clear-is-running
        image: public.ecr.aws/docker/library/alpine:3.21
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            ephemeral-storage: 300M
        command: ["find", "/opt/freesurfer/subjects", "-name", "*IsRunning*", "-delete"]
        mirrorVolumeMounts: true

    container:
      image: "{{workflow.parameters.ecr-registry}}/cloudpipe/fastsurfer:sha-0aae28dd7e437306ca44f6081d4954737b03a056"
      imagePullPolicy: IfNotPresent

      volumeMounts:
      - name: "{{=lower(workflow.parameters.subjID)}}"
        mountPath: /opt/freesurfer/subjects
        subPath: opt/freesurfer/subjects

      env:
        - name: FS_LICENSE
          value: /opt/freesurfer/.license

      command: [bash, -c]
      args: ["/fastsurfer/brun_fastsurfer.sh {{inputs.parameters.argstring}}"]
