argo-events:
  controller:
    nodeSelector:
      eks.amazonaws.com/nodegroup: backend
    tolerations:
    - key: "CriticalAddonsOnly"
      value: "true"
      effect: "NoSchedule"
  webhook:
    nodeSelector:
      eks.amazonaws.com/nodegroup: backend
    tolerations:
    - key: "CriticalAddonsOnly"
      value: "true"
      effect: "NoSchedule"
