apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-handler-sa
    tolerations:
    - key: "CriticalAddonsOnly"
      value: "true"
      effect: "NoSchedule"
  dependencies:
    - name: sqs-source
      eventSourceName: aws-sqs
      eventName: sqs_argo_workflow
      # The following is a workaround for the fact that the SQS event source doesn't support JSON payloads
      # The output of the SQS event source is base64 encoded, so we need to decode it
      transform:
        jq: .body|=@base64d
  triggers:
    - template:
        name: sqs_argo_workflow
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cloudpipe-
                namespace: argo-workflows
              spec:
                arguments:
                  parameters:
                  - name: subjID
                    value: ""
                  - name: globus-source-collection-id
                    value: "${globus_source_collection_id}"
                  - name: globus-source-base-path
                    value: "${globus_source_base_path}"
                  - name: globus-dest-collection-id
                    value: "${globus_dest_collection_id}"
                  - name: globus-dest-base-path
                    value: "${globus_dest_base_path}"
                  - name: globus-scan-types
                    value: '${globus_scan_types}'
                workflowTemplateRef:
                  name: cloudpipe
          parameters:
          - src:
              dependencyName: sqs-source
              dataKey: body
            dest: spec.arguments.parameters.0.value