global:
  amp:
    enabled: true
    prometheusServerEndpoint: "http://localhost:8005/workspaces/ws-3c9d9c35-0b98-420a-b862-d430ad8cb063"
    remoteWriteService: "https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-3c9d9c35-0b98-420a-b862-d430ad8cb063/api/v1/remote_write"
    sigv4:
      region: us-east-2

  grafana:
    enabled: false
    proxy: false

  tolerations:
    - key: "CriticalAddonsOnly"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    eks.amazonaws.com/nodegroup: "backend"

sigV4Proxy:
  region: us-east-2
  host: "aps-workspaces.us-east-2.amazonaws.com"

kubecostProductConfigs:
  clusterName: cloudpipe

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend
  tolerations:
    - key: "CriticalAddonsOnly"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    eks.amazonaws.com/nodegroup: "backend"

localstore:
  tolerations:
    - key: "CriticalAddonsOnly"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    eks.amazonaws.com/nodegroup: "backend"

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model
  tolerations:
    - key: "CriticalAddonsOnly"
      value: "true"
      effect: "NoSchedule"
  nodeSelector:
    eks.amazonaws.com/nodegroup: "backend"

forecasting:
  image:
    repository: public.ecr.aws/kubecost/kubecost-modeling

networkCosts:
  image:
    repository: public.ecr.aws/kubecost/kubecost-network-costs

clusterController:
  image:
    repository: public.ecr.aws/kubecost/cluster-controller

prometheus:
  server:
    global:
      external_labels:
        cluster_id: cloudpipe
    image:
      repository: public.ecr.aws/kubecost/prometheus
    tolerations:
      - key: "CriticalAddonsOnly"
        value: "true"
        effect: "NoSchedule"
    nodeSelector:
      eks.amazonaws.com/nodegroup: "backend"
  serviceAccounts:
    server:
      create: false
      name: kubecost-cost-analyzer-amp

  configmapReload:
    prometheus:
      image:
        repository: public.ecr.aws/kubecost/prometheus-config-reloader

reporting:
  productAnalytics: false

tolerations:
  - key: "CriticalAddonsOnly"
    value: "true"
    effect: "NoSchedule"

nodeSelector:
  eks.amazonaws.com/nodegroup: "backend"
# federatedETL:
#   useMultiClusterDB: true

serviceAccount:
  create: true
  name: kubecost-cost-analyzer-amp