global:
  amp:
    enabled: true
    prometheusServerEndpoint: "http://localhost:8005/workspaces/${amp_workspace_id}"
    remoteWriteService: "https://aps-workspaces.${region}.amazonaws.com/workspaces/${amp_workspace_id}/api/v1/remote_write"
    sigv4:
      region: "${region}"

  grafana:
    enabled: false
    proxy: false

sigV4Proxy:
  region: "${region}"
  host: "aps-workspaces.${region}.amazonaws.com"

kubecostProductConfigs:
  clusterName: ${cluster_name}

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model

forecasting:
  image:
    repository: public.ecr.aws/kubecost/kubecost-modeling

networkCosts:
  image:
    repository: public.ecr.aws/kubecost/kubecost-network-costs

clusterController:
  image:
    repository: public.ecr.aws/kubecost/cluster-controller

prometheus:
  server:
    global:
      external_labels:
        cluster_id: ${cluster_name}
    image:
      repository: public.ecr.aws/kubecost/prometheus
    tolerations:
      - key: "CriticalAddonsOnly"
        value: "true"
        effect: "NoSchedule"
  serviceAccounts:
    server:
      create: false
      name: kubecost-cost-analyzer-amp

  configmapReload:
    prometheus:
      image:
        repository: public.ecr.aws/kubecost/prometheus-config-reloader

reporting:
  productAnalytics: false

# tolerations:
#   - key: "CriticalAddonsOnly"
#     value: "true"
#     effect: "NoSchedule"

# federatedETL:
#   useMultiClusterDB: true

serviceAccount:
  create: true
  name: kubecost-cost-analyzer-amp