tolerations:
- key: "CriticalAddonsOnly"
  value: "true"
  effect: "NoSchedule"

webhook:
  tolerations:
  - key: "CriticalAddonsOnly"
    value: "true"
    effect: "NoSchedule"


cainjector:
  tolerations:
  - key: "CriticalAddonsOnly"
    value: "true"
    effect: "NoSchedule"


# +docs:section=Startup API Check
# This startupapicheck is a Helm post-install hook that waits for the webhook
# endpoints to become available.
# The check is implemented using a Kubernetes Job - if you are injecting mesh
# sidecar proxies into cert-manager pods, ensure that they
# are not injected into this Job's pod. Otherwise, the installation may time out
# owing to the Job never being completed because the sidecar proxy does not exit.
# For more information, see [this note](https://github.com/cert-manager/cert-manager/pull/4414).

startupapicheck:
  tolerations:
  - key: "CriticalAddonsOnly"
    value: "true"
    effect: "NoSchedule"
