apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim
  namespace: argo-workflows
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: fsx-pv
