apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  mountOptions:
    - allow-delete
    - region us-east-2
    - cache-xz abcd-cache-storage--use2-az1--x-s3 # Must be an Express One Zone bucket. More information: https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#shared-cache
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume # Must be unique
    volumeAttributes:
      bucketName: abcd-cache-storage
