apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: subject-data-inventory-workflow-template
  namespace: argo-workflows

spec:

  retryStrategy:
    retryPolicy: "Always"
    limit: "2"

  templates:
  - name: subject-data-inventory-template
    inputs:
      artifacts:
        - name: T1w_Y0
          # Container path where the output will be saved
          path: /home/nonroot/{{workflow.parameters.subjID}}/ses-baselineYear1Arm1/anat/{{workflow.parameters.subjID}}_ses-baselineYear1Arm1_run-01_T1w.nii
          s3:
            key: 'inputs/{{workflow.parameters.subjID}}/ses-baselineYear1Arm1/anat/{{workflow.parameters.subjID}}_ses-baselineYear1Arm1_run-01_T1w.nii'

        - name: T1w_Y2
          path: /home/nonroot/{{workflow.parameters.subjID}}/ses-2YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-2YearFollowUpYArm1_run-01_T1w.nii
          s3:
            key: 'inputs/{{workflow.parameters.subjID}}/ses-2YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-2YearFollowUpYArm1_run-01_T1w.nii'
          optional: true

        - name: T1w_Y4
          path: /home/nonroot/{{workflow.parameters.subjID}}/ses-4YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-4YearFollowUpYArm1_run-01_T1w.nii
          optional: true
          s3:
            key: 'inputs/{{workflow.parameters.subjID}}/ses-4YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-4YearFollowUpYArm1_run-01_T1w.nii'

        - name: T1w_Y6
          path: /home/nonroot/{{workflow.parameters.subjID}}/ses-6YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-6YearFollowUpYArm1_run-01_T1w.nii
          optional: true
          s3:
            key: 'inputs/{{workflow.parameters.subjID}}/ses-6YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-6YearFollowUpYArm1_run-01_T1w.nii'

        - name: T1w_Y8
          path: /home/nonroot/{{workflow.parameters.subjID}}/ses-8YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-8YearFollowUpYArm1_run-01_T1w.nii
          optional: true
          s3:
            key: 'inputs/{{workflow.parameters.subjID}}/ses-8YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-8YearFollowUpYArm1_run-01_T1w.nii'

        - name: T1w_Y10
          path: /home/nonroot/{{workflow.parameters.subjID}}/ses-10YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-10YearFollowUpYArm1_run-01_T1w.nii
          optional: true
          s3:
            key: 'inputs/{{workflow.parameters.subjID}}/ses-10YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-10YearFollowUpYArm1_run-01_T1w.nii'
    script:
      image: public.ecr.aws/docker/library/python:3-slim-bullseye
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          ephemeral-storage: 50M
      command: [python]
      source: |
        from pathlib import Path
        import json
        import time

        # Possible race condition here?
        time.sleep(30)

        T1w_sessions = [p.name.split('_')[1] for p in Path('/home/nonroot/{{workflow.parameters.subjID}}/').rglob('*_T1w.nii') if p.is_file()]
        print(json.dumps(T1w_sessions))
