apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-handler-sa
    tolerations:
    - key: "argoproj.io/backend"
      value: "true"
      effect: "NoSchedule"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: In
              values:
              - argo

  dependencies:
    - name: sqs-source
      eventSourceName: aws-sqs
      eventName: sqs_argo_workflow
      # The following is a workaround for the fact that the SQS event source doesn't support JSON payloads
      # The output of the SQS event source is base64 encoded, so we need to decode it
      transform:
        jq: .body|=@base64d
  triggers:
    - template:
        name: sqs_argo_workflow
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cloudpipe-workflow-
                namespace: argo-workflows
              spec:
                arguments:
                  parameters:
                  - name: ndaGUID
                    value: ""
                workflowTemplateRef:
                  name: cloudpipe-long-master-workflow-template
          parameters:
          - src:
              dependencyName: sqs-source
              dataKey: body
            dest: spec.arguments.parameters.0.value