apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: al2023-gpu-nodepool
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023-gpu-nodeclass
      # Avoid possible race between the scheduler and the CSINode
      # see https://karpenter.sh/docs/troubleshooting/#pods-were-scheduled-due-to-a-race-condition-in-kubernetes
      startupTaints:
      - key: ebs.csi.aws.com/agent-not-ready
        effect: NoExecute
      - key: efs.csi.aws.com/agent-not-ready
        effect: NoExecute
      requirements:
      # see: https://karpenter.sh/docs/concepts/scheduling/#well-known-labels
      # AMD64
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      # Runs linux
      - key: "kubernetes.io/os"
        operator: In
        values: ["linux"]
      # Spot/On-demand instances
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot", "on-demand"]
      # Nitro instances are required for using prefixes to expand ip addresses
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: In
        values: ["nitro"]
      - key: "karpenter.k8s.aws/instance-local-nvme"
        operator: Gt
        values: ["74"]
      - key: "karpenter.k8s.aws/instance-gpu-manufacturer"
        operator: In
        values: ["nvidia"]
      - key: "karpenter.k8s.aws/instance-family"
        operator: In
        values: ["g4dn","g5", "g5g", "g6", "g6e", "p2", "p3", "p5"]

