apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: al2023-nodeclass
spec:
  amiSelectorTerms:
  - alias: al2023@latest
  instanceStorePolicy: RAID0

  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  detailedMonitoring: true
  role: ${ karpenter_node_iam_role_name }
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${ eks_cluster_name }
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${ eks_cluster_name }
