apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: al2023-intel-light-nodepool
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023-nodeclass
      # Avoid possible race between the scheduler and the CSINode
      # see https://karpenter.sh/docs/troubleshooting/#pods-were-scheduled-due-to-a-race-condition-in-kubernetes
      startupTaints:
      - key: ebs.csi.aws.com/agent-not-ready
        effect: NoExecute
      - key: efs.csi.aws.com/agent-not-ready
        effect: NoExecute
      requirements:
      # see: https://karpenter.sh/docs/concepts/scheduling/#well-known-labels
      # AMD64 (x86_64)
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      # Runs linux
      - key: "kubernetes.io/os"
        operator: In
        values: ["linux"]
      # Nitro instances are required for using prefixes to expand ip addresses
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: In
        values: ["nitro"]
      # Spot instances
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["spot", "on-demand"]
      # Instance category (letter at the beginning of an instance type)
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["t", "c", "m", "r"]
      - key: "karpenter.k8s.aws/instance-local-nvme"
        operator: Gt
        values: ["74"]