
admissionWebhooks:
  namespaceSelector:
  objectSelector:
affinity:
collector:
  # containerLogs:
  #   exporters:
  #     awscloudwatchlogs:
  #       # Can be 1-512 characters including any of [\.\-_/#A-Za-z0-9]+
  #       log_group_name:
  #       # Can be 1-512 characters, including any of [^:*]*
  #       log_stream_name:
  #   pipelines:
  #     logs:
  #       cloudwatchLogs:
  #         enabled:
  #   resources:
  #     limits:
  #       cpu:
  #       memory:
  #     requests:
  #       cpu:
  #       memory:
  #   serviceAccount:
  #     annotations:
  otlpIngest:
    pipelines:
      traces:
        xray:
          enabled:
    resources:
      limits:
        cpu:
        memory:
      requests:
        cpu:
        memory:
    serviceAccount:
      annotations:
  prometheusMetrics:
    exporters:
      prometheusremotewrite:
        endpoint:
    pipelines:
      metrics:
        amp:
          enabled:
        emf:
          enabled:
    resources:
      limits:
        cpu:
        memory:
      requests:
        cpu:
        memory:
    serviceAccount:
      annotations:
  kubeRBACProxy:
    enabled: true
    resources:
      limits:
        cpu:
        memory:
      requests:
        cpu:
        memory:
  manager:
    env:
    resources:
      limits:
        cpu:
        memory:
      requests:
        cpu:
        memory:
  nodeSelector:
  replicaCount:
  tolerations: