apiVersion: v2
name: aws-ebs-csi-driver
description: A Helm chart for AWS EBS CSI Driver
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: aws-ebs-csi-driver
    version: 2.36.0
    repository: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
