apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: al2023-cpu-heavy-nodepool
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023-nodeclass
      # Avoid possible race between the scheduler and the CSINode
      # see https://karpenter.sh/docs/troubleshooting/#pods-were-scheduled-due-to-a-race-condition-in-kubernetes
      requirements:
      # see: https://karpenter.sh/docs/concepts/scheduling/#well-known-labels
      # AMD64
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"] # In Go, amd64 means x86_64
      # Runs linux
      - key: "kubernetes.io/os"
        operator: In
        values: ["linux"]
      # Spot instances
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]
      # Instance category (first letter)
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m", "r"]
      # Nitro instances are required for using prefixes to expand ip addresses
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: In
        values: ["nitro"]
      # Instance generation
      # Karpenter recommends this setting: https://karpenter.sh/docs/concepts/nodepools/#min-values
      - key: "karpenter.k8s.aws/instance-generation"
        operator: Gt
        values: ["2"]
      - key: "karpenter.k8s.aws/instance-local-nvme"
        operator: Gt
        values: ["74"]
