apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: globus-credentials
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: globus-credentials
    creationPolicy: Owner
  data:
    - secretKey: native-app-client-id
      remoteRef:
        key: globus/refresh-token
        property: native-app-client-id
    - secretKey: refresh-token
      remoteRef:
        key: globus/refresh-token
        property: refresh-token
