apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: inventory
  namespace: argo-workflows

spec:
  templates:

  - name: subject-data-inventory-template
    metadata:
      labels:
        cloudpipe.io/phase: inventory
        cloudpipe.io/step: subject-data-inventory
    retryStrategy:
      limit: "3"
      retryPolicy: OnFailure
      backoff:
        duration: "30s"
        factor: "2"
    nodeSelector:
      karpenter.sh/nodepool: cpu-light-nodepool

    outputs:
      parameters:
        - name: fastsurfer-exists
          valueFrom:
            path: /tmp/fastsurfer_exists.txt
        - name: subregions-exist
          valueFrom:
            path: /tmp/subregions_exists.txt

    container:
      image: "{{workflow.parameters.ecr-registry}}/cloudpipe/python:sha-db370b69f7fa6cef8138b23dd811b5f9af8d17d5"
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
          ephemeral-storage: 500M
        limits:
          ephemeral-storage: 500M
      env:
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: cloudpipe-config
              key: region
      command: [python, /app/inventory.py]
      args:
        - --subject
        - '{{workflow.parameters.subjID}}'
        - --bucket
        - '{{workflow.parameters.bucket}}'
