name: deploy-to-docker
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build GPU-enabled Docker Image
      run: python Docker/build.py --device cuda --tag ${{ secrets.DOCKERHUB_USERNAME }}/fastProc:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        NDA_PASSWORD: ${{ secrets.NDA_PASSWORD }}
        NDA_USERNAME: ${{ secrets.NDA_USERNAME }}
        MINDAR_PASSWORD: ${{ secrets.MINDAR_PASSWORD }}
        MINDAR_HOST: ${{ secrets.MINDAR_HOST }}
    - name: Push the Docker Image
      run: docker push
