apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  storageClassName: fsx-sc
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: ${filesystem_id}
    volumeAttributes:
      dnsname: ${filesystem_id}.fsx.${region}.amazonaws.com
      mountname: ${mountname}
