apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: fmriprep-workflow-template-
  namespace: argo-workflows
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true
  
  arguments:
    parameters:
      - name: subjID
        value: "sub-NDARINV9BBUE6LG"
      - name: T1w_sessions
        value: ["ses-baselineYear1Arm1", "ses-2YearFollowUpYArm1"]

  templates:
  - name: fmriprep-loop-template
    inputs:
      parameters:
        - name: T1w_sessions
          value: "{{workflow.parameters.T1w_sessions}}"
    steps:
    - - name: fmriprep-loop-step
        template: fmriprep-template
        arguments:
          parameters:
            - name: session
              value: "{{item}}"
        withItems: [ "{{workflow.parameters.T1w_sessions}}"]

  - name: fmriprep-template
    inputs:
      parameters:
        - name: session
      
      artifacts:
      #--- BIDS Dataset Description ---# (fmriprep will fail to recognize the input if this is missing)
      - name: dataset-description
        path: /home/fmriprep/input/dataset_description.json
        s3:
          key: 'inputs/dataset_description.json'


      #--- Freesurfer License ---# (fmriprep uses Freesurfer tools, ergo a license is required)
      - name: fslicense
        path: /home/fmriprep/.license
        s3:
          key: 'config/fslicense'

      #--- FastSurfer Output ---#
      # see: https://fmriprep.org/en/stable/usage.html#using-a-previous-run-of-freesurfer
      - name: fastsurfer-output
        path: /home/fmriprep/output/sourcedata/freesurfer/{{workflow.parameters.subjID}}
        s3:
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{workflow.parameters.subjID}}-long-complete.tar.gz'

      # fmriprep requires fsaverage to generate cifti output
      - name: fsaverage
        path: /home/fmriprep/output/sourcedata/freesurfer/fsaverage
        s3:
          key: 'config/fsaverage'

      #--- Anatomicals ---# (fmriprep uses these for alignment, even if pre-computed Freesurfer derivatives are passed)

      # T1w
      ## NIFTI
      - name: T1w
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.nii'
      ## JSON
      - name: T1w-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.json'
      
      # T2w (optional)
      ## NIFTI
      - name: T2w
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T2w.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T2w.nii'
        optional: true
      ## JSON
      - name: T2w-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T2w.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.json'
        optional: true

      #--- Functionals ---#

      # Resting State
      ## Run-01
      ### NIFTI
      - name: rest-run-1
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-01_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-01_bold.nii'
      ### JSON
      - name: rest-run-1-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-01_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-01_bold.json'
      
      ## Run-02
      ### NIFTI
      - name: rest-run-2
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-02_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-02_bold.nii'
      - name: rest-run-2-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-02_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-02_bold.json'
      
      ## Run-03
      ### NIFTI
      - name: rest-run-3
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-03_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-03_bold.nii'
      ### JSON
      - name: rest-run-3-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-03_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-03_bold.json'
      
      ## Run-04
      ### NIFTI
      - name: rest-run-4
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-04_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-04_bold.nii'
      ### JSON
      - name: rest-run-4-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-04_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-04_bold.json'

      ## Run-05
      ### NIFTI
      - name: rest-run-5
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-05_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-05_bold.nii'
        optional: true
      ### JSON
      - name: rest-run-5-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-05_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-05_bold.json'
        optional: true

      ## Run-06
      ### NIFTI
      - name: rest-run-6
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-06_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-06_bold.nii'
        optional: true
      ### JSON
      - name: rest-run-6-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-06_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-06_bold.json'
        optional: true

      # N-Back

      ## Run-01
      ### NIFTI
      - name: nback-run-1
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-01_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-01_bold.nii'
      ### JSON
      - name: nback-run-1-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-01_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-01_bold.json'
      
      ## Run-02
      ### NIFTI
      - name: nback-run-2
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-02_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-02_bold.nii'
      ### JSON
      - name: nback-run-2-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-02_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-02_bold.json'
      
      ## Run-03
      ### NIFTI
      - name: nback-run-3
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-03_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-03_bold.nii'
        optional: true
      ### JSON
      - name: nback-run-3-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-03_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-03_bold.json'
        optional: true

      ## Run-04
      ### NIFTI
      - name: nback-run-4
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-04_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-04_bold.nii'
        optional: true
      ### JSON
      - name: nback-run-4-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-04_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-04_bold.json'
        optional: true

    outputs:
      artifacts:
      - name: fmriprep-output
        path: /home/fmriprep/output/{{workflow.parameters.subjID}}/{{workflow.parameters.ses}}
        s3:
          key: 'derivatives/fmriprep/{{workflow.parameters.subjID}}/{{workflow.parameters.ses}}/fmriprep-output.tar.gz'

    nodeSelector:
      karpenter.sh/nodepool: al2023-cpuheavy-nodepool
    
    container:
      securityContext:
        runAsUser: 0
      imagePullPolicy: IfNotPresent
      image: public.ecr.aws/w5b6h0h5/fmriprep:latest
      env:
        - name: ARGO_DEBUG_PAUSE_AFTER
          value: 'true'
      resources:
        requests:
          memory: 16Gi
          cpu: 4000m
      args:
        - '--nprocs'
        - '4'
        - '--omp-nthreads'
        - '4'
        - '--mem'
        - '16000'
        - '--skip-bids-validation'
        - '--fs-license-file'
        - '/home/fmriprep/.license'
        - '--fs-subjects-dir'
        - '/home/fmriprep/output/sourcedata/freesurfer'
        - '--fs-no-reconall'
        # ABCD MinProc data is already fieldmap corrected (source?)
        - '--ignore'
        - 'fieldmaps'
        - '--cifti-output'
        - '170k'
        # Include these arguments to ensure replicable outputs
        - '--skull-strip-fixed-seed'
        - '--random-seed'
        - '52618'
        - '/home/fmriprep/input'
        - '/home/fmriprep/output'
        - 'participant'
