apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fastsurfer-template-creation-workflow-template
  namespace: argo-workflows
spec: 
  serviceAccountName: argo-workflows-s3access

  # TO DO: Verify this is necessary given that we're already specifying
  # security context in the parent workflow template
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    supplementalGroups:
      - 1000
    runAsNonRoot: true
            
  templates:
  - name: fastsurfer-template-creation-dag-template

    inputs:
      parameters:
        - name: T1w_sessions

    dag:
      tasks: 
      - name: generate-fastsurfer-command-string-dagtask
        template: generate-fastsurfer-command-string-template
        arguments:
          parameters:
            - name: T1w_sessions
              value: "{{inputs.parameters.T1w_sessions}}"

      - name: fastsurfer-template-creation-dagtask
        template: fastsurfer-template-creation-template
        arguments:
          parameters:
            - name: fastsurfer-command-string
              value: "{{tasks.generate-fastsurfer-command-string-dagtask.outputs.result}}"
        dependencies:
          - generate-fastsurfer-command-string-dagtask

  - name: generate-fastsurfer-command-string-template
    inputs:
      parameters:
        - name: T1w_sessions

    script:
      image: python:alpine3.21
      command: [python]
      source: |
        import os
        sessions = {{inputs.parameters.T1w_sessions}}
        subjid = "{{workflow.parameters.subjID}}"
        T1s = [f'/home/nonroot/{subjid}/{session}/anat/{subjid}_{session}_run-01_T1w.nii' for session in sessions]
        cmdstring = " ".join(['--tid', "_".join([subjid, "template"]), '--t1s', *T1s, '--tpids', *sessions, '--threads', '4'])
        print(cmdstring)

  # NOTE: The code in long_prepare_template.sh will automagically handle timepoints with only baseline data
  - name: fastsurfer-template-creation-template
    inputs:
      parameters:
        - name: fastsurfer-command-string

      artifacts:
      - name: fslicense
        path: '/opt/freesurfer/.license'
        s3:
          key: 'config/fslicense'

      - name: fsaverage
        path: '/opt/freesurfer/subjects/fsaverage'
        s3:
          key: 'config/fsaverage/'

      - name: T1w_Y0
        path: /home/nonroot/{{workflow.parameters.subjID}}/ses-baselineYear1Arm1/anat/{{workflow.parameters.subjID}}_ses-baselineYear1Arm1_run-01_T1w.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/ses-baselineYear1Arm1/anat/{{workflow.parameters.subjID}}_ses-baselineYear1Arm1_run-01_T1w.nii'

      - name: T1w_Y2
        path: /home/nonroot/{{workflow.parameters.subjID}}/ses-2YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-2YearFollowUpYArm1_run-01_T1w.nii
        # FastSurfer appropriately handles single timepoint inputs to its longitudinal workflow
        optional: true
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/ses-2YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-2YearFollowUpYArm1_run-01_T1w.nii'

      - name: T1w_Y4
        path: /home/nonroot/{{workflow.parameters.subjID}}/ses-4YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-4YearFollowUpYArm1_run-01_T1w.nii
        optional: true
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/ses-4YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-4YearFollowUpYArm1_run-01_T1w.nii'

      - name: T1w_Y6
        path: /home/nonroot/{{workflow.parameters.subjID}}/ses-6YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-6YearFollowUpYArm1_run-01_T1w.nii
        optional: true
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/ses-6YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-6YearFollowUpYArm1_run-01_T1w.nii'

      - name: T1w_Y8
        path: /home/nonroot/{{workflow.parameters.subjID}}/ses-8YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-8YearFollowUpYArm1_run-01_T1w.nii
        optional: true
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/ses-8YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-8YearFollowUpYArm1_run-01_T1w.nii'

      - name: T1w_Y10
        path: /home/nonroot/{{workflow.parameters.subjID}}/ses-10YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-10YearFollowUpYArm1_run-01_T1w.nii
        optional: true
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/ses-10YearFollowUpYArm1/anat/{{workflow.parameters.subjID}}_ses-10YearFollowUpYArm1_run-01_T1w.nii'

    nodeSelector:
      karpenter.sh/nodepool: al2023-gpu-nodepool

    container:
      imagePullPolicy: IfNotPresent
      image: public.ecr.aws/l9e7l1h1/cloudpipe/fastsurfer:latest
      
      volumeMounts:
      - name: workdir
        mountPath: /opt/freesurfer/subjects

      env:
        - name: FS_LICENSE
          value: /opt/freesurfer/.license

      resources:
        requests:
          memory: 16Gi
          cpu: 4000m
        limits:
          nvidia.com/gpu: '1'
          
      command: [bash, -c]
      args: ["/fastsurfer/recon_surf/long_prepare_template.sh {{inputs.parameters.fastsurfer-command-string}}"]


