apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fastsurfer-segmentation-workflow-template
  namespace: argo-workflows
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true

  templates:
  - name: fastsurfer-segmentation-template

    # Files coming in...
    inputs:
      artifacts:
      - name: T1w
        # Container path where the output will be saved
        path: /home/nonroot/{{workflow.parameters.subjID}}_ses-baselineYear1Arm1_run-01_T1w.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/ses-baselineYear1Arm1/anat/{{workflow.parameters.subjID}}_ses-baselineYear1Arm1_run-01_T1w.nii'

    # Files going out...
    outputs:
      artifacts:
      - name: segmentation-output
        path: '/opt/freesurfer/subjects/{{workflow.parameters.subjID}}/'
        s3:
          # Workflows will automatically compress the output artifact, but we need to manually add the .tar.gz
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/ses-baselineYear1Arm1/{{workflow.parameters.subjID}}_ses-baselineYear1Arm1-segmentation.tar.gz/'

    nodeSelector:
      karpenter.sh/nodepool: al2023-gpu-nodepool

    container:
      imagePullPolicy: IfNotPresent
      # deepmi/fastsurfer does NOT explicitly add a nonroot user to the image - which seems to be a requirement for containerd
      # we'll just create a variant that does add the nonroot user (and their user directory)
      image: public.ecr.aws/l9e7l1h1/cloudpipe/fastsurfer:latest
      resources:
        requests:
          memory: 16Gi
          cpu: 4000m
        limits:
          nvidia.com/gpu: '1'

      # Formatting below from https://github.com/argoproj/argo-workflows/blob/main/examples/artifact-path-placeholders.yaml
      args:
        - '--t1'
        - '{{inputs.artifacts.T1w.path}}'
        - '--sid'
        - '{{workflow.parameters.subjID}}'
        - '--seg_only'
        - '--parallel'
        - '--3T'
        - '--threads'
        - '4'
        - '--no_cereb'
        - '--no_biasfield'
