apiVersion: v2
name: argo-workflows
description: A Helm chart for Argo Workflows
type: application
version: 0.1.0
appVersion: "v4.1.3"
dependencies:
  - name: argo-workflows
    version: 2.0.6
    repository: https://argoproj.github.io/argo-helm
  - name: pgbouncer
    version: 4.1.9
    repository: https://icoretech.github.io/helm
