apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fastsurfer-template-segmentation-workflow-template
  namespace: argo-workflows
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true

  templates:
  - name: fastsurfer-template-segmentation-template

    nodeSelector:
      karpenter.sh/nodepool: al2023-gpu-nodepool

    container:
      imagePullPolicy: IfNotPresent
      # deepmi/fastsurfer does NOT explicitly add a nonroot user to the image - which seems to be a requirement for containerd
      # we'll just create a variant that does add the nonroot user (and their user directory)
      image: public.ecr.aws/l9e7l1h1/cloudpipe/fastsurfer:latest
      
      volumeMounts:
      - name: workdir
        mountPath: /opt/freesurfer/subjects

      resources:
        requests:
          memory: 16Gi
          cpu: 8000m
        limits:
          nvidia.com/gpu: '1'

      args:
        - '--sid'
        - '{{workflow.parameters.subjID}}_template'
        - '--sd'
        - '/opt/freesurfer/subjects'
        - '--base'
        - '--seg_only'
        - '--threads'
        - '8'

