apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fastsurfer-long-segmentation-workflow-template
  namespace: argo-workflows
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    runAsNonRoot: true

  templates:
  - name: fastsurfer-long-segmentation-steps-template
    inputs:
      parameters:
        - name: T1w_sessions

    steps:
    - - name: createargstring
        template: createargstring-template
        arguments:
          parameters:
            - name: T1w_sessions
              value: '{{inputs.parameters.T1w_sessions}}'
    
    - - name: fastsurfer-long-segmentation-step
        template: fastsurfer-long-segmentation-template
        arguments:
          parameters:
            - name: argstring
              value: '{{steps.createargstring.outputs.result}}'

  # Per lines 311:313 of long_fastsurfer.sh, need to wrap sessions in quotes and append each incoming session with "=from-base" 
  - name: createargstring-template
    inputs:
      parameters:
        - name: T1w_sessions
    
    script:
      image: python:3.12.9-slim-bookworm
      command: [python]
      source: |
        import os
        T1w_sessions = {{inputs.parameters.T1w_sessions}}
        subjid = "{{workflow.parameters.subjID}}"
        subjidwtmpl = str(subjid + "_template")
        # Appending '=from-base' to all sessions except the last
        T1w_sessions = [session + "=from-base" for session in T1w_sessions]
        argstring = ' '.join(['--subjects', ' '.join([*T1w_sessions]), '--sd', '/opt/freesurfer/subjects', '--seg_only', '--fsaparc', '--long', f'{subjidwtmpl}', '--threads', '8'])
        print(argstring)

  - name: fastsurfer-long-segmentation-template
  
    inputs:
      parameters:
        - name: argstring

    nodeSelector:
      karpenter.sh/nodepool: al2023-gpu-nodepool

    container:
      imagePullPolicy: IfNotPresent
      # deepmi/fastsurfer does NOT explicitly add a nonroot user to the image - which seems to be a requirement for containerd
      # we'll just create a variant that does add the nonroot user (and their user directory)
      image: public.ecr.aws/l9e7l1h1/cloudpipe/fastsurfer:latest

      volumeMounts:
      - name: workdir
        mountPath: /opt/freesurfer/subjects

      resources:
        requests:
          memory: 16Gi
          cpu: 8000m
        limits:
          nvidia.com/gpu: '1'

      command: [bash, -c]
      args: ["/fastsurfer/brun_fastsurfer.sh {{inputs.parameters.argstring}}"]
