apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fmriprep-workflow-template
  generateName: fmriprep-workflow-template-
  namespace: argo-workflows
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::026415314835:role/argo-workflows-s3access
spec:
  templates:
  # As of v3.6.4, loops can only be used inside a DAG or steps
  - name: fmriprep-loop-template
    # Setting parallelism = 1 ensures only one session is processed at a time
    # Each session is processed on the same node (?...verify this), so if we want to turn this up, we need larger nodes
    parallelism: 1
    inputs:
      parameters:
        - name: T1w_sessions

    # Workflow loops can only be done inside a steps or DAG template :(
    steps:
    - - name: fmriprep-loop-step
        template: fmriprep-template
        arguments:
          parameters:
            - name: session
              value: '{{item}}'
        withParam: '{{inputs.parameters.T1w_sessions}}'

  - name: fmriprep-template

    # Clear out the fmriprep folder
    # Since we're in a steps loop, we'll end up reusing the same node and volume
    # and argo workflows will complain about files/directories already existing
    initContainers:
    - name: clearvolume
      image: alpine:latest
      command: ["rm", "-rf", "/home/fmriprep/*"]
      mirrorVolumeMounts: true

    inputs:
      parameters:
        - name: session
      
      artifacts:
      #--- BIDS Dataset Description ---# (fmriprep will fail to recognize the input if this is missing)
      - name: dataset-description
        path: /home/fmriprep/input/dataset_description.json
        s3:
          key: 'inputs/dataset_description.json'

      #--- Freesurfer License ---# (fmriprep uses Freesurfer tools, ergo a license is required)
      - name: fslicense
        path: /home/fmriprep/.license
        s3:
          key: 'config/fslicense'

      #--- FastSurfer Output ---#
      # see: https://fmriprep.org/en/stable/usage.html#using-a-previous-run-of-freesurfer
      # Here we pull in a segmented, parcellated, and within-subjects template aligned anatomical for the specified session
      # However, fmriprep is expecting a directory name matching the subject ID (NOT the session), so we'll just unpack to that path.
      - name: fastsurfer-templated-session
        path: /home/fmriprep/output/sourcedata/freesurfer/{{workflow.parameters.subjID}}
        s3:
          key: 'derivatives/fastsurfer/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}_templated.tar.gz'

      # fmriprep requires fsaverage to generate cifti output
      - name: fsaverage
        path: /home/fmriprep/output/sourcedata/freesurfer/fsaverage
        s3:
          key: 'config/fsaverage'

      #--- Anatomicals ---# (fmriprep uses these for alignment, even if pre-computed Freesurfer derivatives are passed)
      # T1w
      ## NIFTI
      - name: T1w
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.nii'
      ## JSON
      - name: T1w-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.json'
      
      # T2w (optional)
      ## NIFTI
      - name: T2w
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T2w.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T2w.nii'
        optional: true
      ## JSON
      - name: T2w-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T2w.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/anat/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_run-01_T1w.json'
        optional: true

      #--- Functionals ---#
      # Resting State (we'll assume there may be as many as six rsfmri runs)
      ## Run-01
      ### NIFTI
      - name: rest-run-1
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-01_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-01_bold.nii'
        optional: true
      ### JSON
      - name: rest-run-1-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-01_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-01_bold.json'
        optional: true
      
      ## Run-02
      ### NIFTI
      - name: rest-run-2
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-02_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-02_bold.nii'
        optional: true
      - name: rest-run-2-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-02_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-02_bold.json'
        optional: true
      
      ## Run-03
      ### NIFTI
      - name: rest-run-3
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-03_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-03_bold.nii'
        optional: true
      ### JSON
      - name: rest-run-3-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-03_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-03_bold.json'
        optional: true
      
      ## Run-04
      ### NIFTI
      - name: rest-run-4
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-04_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-04_bold.nii'
        optional: true
      ### JSON
      - name: rest-run-4-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-04_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-04_bold.json'
        optional: true

      ## Run-05
      ### NIFTI
      - name: rest-run-5
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-05_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-05_bold.nii'
        optional: true
      ### JSON
      - name: rest-run-5-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-05_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-05_bold.json'
        optional: true

      ## Run-06
      ### NIFTI
      - name: rest-run-6
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-06_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-06_bold.nii'
        optional: true
      ### JSON
      - name: rest-run-6-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-06_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-rest_run-06_bold.json'
        optional: true

      # N-Back (assuming a possible maximum of four runs)

      ## Run-01
      ### NIFTI
      - name: nback-run-1
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-01_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-01_bold.nii'
        optional: true

      ### JSON
      - name: nback-run-1-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-01_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-01_bold.json'
        optional: true

      ## Run-02
      ### NIFTI
      - name: nback-run-2
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-02_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-02_bold.nii'
        optional: true
      ### JSON
      - name: nback-run-2-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-02_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-02_bold.json'
        optional: true
      
      ## Run-03
      ### NIFTI
      - name: nback-run-3
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-03_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-03_bold.nii'
        optional: true
      ### JSON
      - name: nback-run-3-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-03_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-03_bold.json'
        optional: true

      ## Run-04
      ### NIFTI
      - name: nback-run-4
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-04_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-04_bold.nii'
        optional: true
      ### JSON
      - name: nback-run-4-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-04_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-nback_run-04_bold.json'
        optional: true

      # SST
      ## Run-01
      ### NIFTI
      - name: sst-run-1
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-sst_run-01_bold.nii
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-sst_run-01_bold.nii'
        optional: true
      ### JSON
      - name: sst-run-1-json
        path: /home/fmriprep/input/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-sst_run-01_bold.json
        s3:
          key: 'inputs/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/func/{{workflow.parameters.subjID}}_{{inputs.parameters.session}}_task-sst_run-01_bold.json'
        optional: true

    outputs:
      artifacts:
      - name: fmriprep-output
        path: /home/fmriprep/output/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}
        s3:
          key: 'derivatives/fmriprep/{{workflow.parameters.subjID}}/{{inputs.parameters.session}}/fmriprep-output.tar.gz'

    nodeSelector:
      karpenter.sh/nodepool: al2023-cpuheavy-nodepool
    
    container:
      # fmriprep crashes hard when its not run as root - too lazy to resolve this
      securityContext:
        runAsUser: 0
      imagePullPolicy: IfNotPresent
      # Pull from our public repository containing slightly modified fmriprep images
      image: public.ecr.aws/w5b6h0h5/fmriprep:latest

      # CANNOT USE VOLUMES - no way to pass fmriprep the templated session in a folder renamed after the subject ID
      # Mount the FastSurfer session output folder using the subjectID
      # This seems to be what fmriprep is looking for when using pre-computed FS derivatives
      # volumeMounts:
      # - name: workdir
      #   mountPath: '/home/fmriprep/output/sourcedata/freesurfer/{{workflow.parameters.subjID}}_template'

      resources:
        requests:
          memory: 16Gi
          cpu: 4000m
          
      args:
        - '--nprocs'
        - '4'
        - '--omp-nthreads'
        - '4'
        - '--mem'
        - '16000'
        - '--skip-bids-validation'
        - '--fs-license-file'
        - '/home/fmriprep/.license'
        - '--fs-subjects-dir'
        - '/home/fmriprep/output/sourcedata/freesurfer'
        # Do not attempt to 'resume' recon-all from precomputed derivatives
        - '--fs-no-resume'
        # ABCD MinProc data is already fieldmap corrected (source?)
        - '--ignore'
        - 'fieldmaps'
        # As of 24.1.1, CIFTI output cannot be generated without running recon-all
        # - '--cifti-output'
        # - '170k'
        # Include these arguments to ensure replicable outputs
        - '--skull-strip-fixed-seed'
        - '--random-seed'
        - '52618'
        - '/home/fmriprep/input'
        - '/home/fmriprep/output'
        - 'participant'
