apiVersion: eks.services.k8s.aws/v1alpha1
kind: AddonConfiguration
metadata:
  name: cloudwatch-observability-config
spec:
  agent:
    autoGenerateCert:
      enabled: true
    mode: deployment
    nodeSelector:
      default:
        kubernetes.io/os: linux
    otelConfig: {}
    prometheus:
      config: {}
      targetAllocator:
        enabled: true
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 128Mi
  containerLogs:
    enabled: true
    # Default fluentbit config for ACWO is at: https://github.com/aws-observability/helm-charts/blob/v1.7.0/charts/amazon-cloudwatch-observability/values.yaml
    fluentBit:
      config:
        service: |
          [SERVICE]
            Flush                     5
            Grace                     30
            Log_Level                 error
            Daemon                    off
            Parsers_File              parsers.conf
            storage.path              /var/fluent-bit/state/flb-storage/
            storage.sync              normal
            storage.checksum          off
            storage.backlog.mem_limit 5M
        customParsers: |
          [PARSER]
            Name                syslog
            Format              regex
            Regex               ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
            Time_Key            time
            Time_Format         %b %d %H:%M:%S
    
          [PARSER]
            Name                container_firstline
            Format              regex
            Regex               (?<log>(?<="log":")\S(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
            Time_Key            time
            Time_Format         %Y-%m-%dT%H:%M:%S.%LZ
      
          [PARSER]
            Name                cwagent_firstline
            Format              regex
            Regex               (?<log>(?<="log":")\d{4}[\/-]\d{1,2}[\/-]\d{1,2}[ T]\d{2}:\d{2}:\d{2}(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
            Time_Key            time
            Time_Format         %Y-%m-%dT%H:%M:%S.%LZ
        extraFiles:
          application-log.conf: |
            [INPUT]
              Name                tail
              Tag                 application.*
              Exclude_Path        /var/log/containers/cloudwatch-agent*, /var/log/containers/fluent-bit*, /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
              Path                /var/log/containers/*.log
              multiline.parser    docker, cri
              DB                  /var/fluent-bit/state/flb_container.db
              Mem_Buf_Limit       50MB
              Skip_Long_Lines     On
              Refresh_Interval    10
              Rotate_Wait         30
              storage.type        filesystem
              Read_from_Head      ${READ_FROM_HEAD}
        
            [INPUT]
              Name                tail
              Tag                 application.*
              Path                /var/log/containers/fluent-bit*
              multiline.parser    docker, cri
              DB                  /var/fluent-bit/state/flb_log.db
              Mem_Buf_Limit       5MB
              Skip_Long_Lines     On
              Refresh_Interval    10
              Read_from_Head      ${READ_FROM_HEAD}
        
            [INPUT]
              Name                tail
              Tag                 application.*
              Path                /var/log/containers/cloudwatch-agent*
              multiline.parser    docker, cri
              DB                  /var/fluent-bit/state/flb_cwagent.db
              Mem_Buf_Limit       5MB
              Skip_Long_Lines     On
              Refresh_Interval    10
              Read_from_Head      ${READ_FROM_HEAD}
        
            [FILTER]
              Name                kubernetes
              Match               application.*
              Kube_URL            https://kubernetes.default.svc:443
              Kube_Tag_Prefix     application.var.log.containers.
              Merge_Log           On
              Merge_Log_Key       log_processed
              K8S-Logging.Parser  On
              K8S-Logging.Exclude Off
              Labels              Off
              Annotations         Off
              Use_Kubelet         On
              Kubelet_Port        10250
              Buffer_Size         0
        
            [OUTPUT]
              Name                cloudwatch_logs
              Match               application.*
              region              ${AWS_REGION}
              log_group_name      /aws/containerinsights/${CLUSTER_NAME}/application
              log_stream_prefix   ${HOST_NAME}-
              auto_create_group   true
              extra_user_agent    container-insights
          dataplane-log.conf: |
            [INPUT]
              Name                systemd
              Tag                 dataplane.systemd.*
              Systemd_Filter      _SYSTEMD_UNIT=docker.service
              Systemd_Filter      _SYSTEMD_UNIT=containerd.service
              Systemd_Filter      _SYSTEMD_UNIT=kubelet.service
              DB                  /var/fluent-bit/state/systemd.db
              Path                /var/log/journal
              Read_From_Tail      ${READ_FROM_TAIL}
        
            [INPUT]
              Name                tail
              Tag                 dataplane.tail.*
              Path                /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
              multiline.parser    docker, cri
              DB                  /var/fluent-bit/state/flb_dataplane_tail.db
              Mem_Buf_Limit       50MB
              Skip_Long_Lines     On
              Refresh_Interval    10
              Rotate_Wait         30
              storage.type        filesystem
              Read_from_Head      ${READ_FROM_HEAD}
        
            [FILTER]
              Name                modify
              Match               dataplane.systemd.*
              Rename              _HOSTNAME                   hostname
              Rename              _SYSTEMD_UNIT               systemd_unit
              Rename              MESSAGE                     message
              Remove_regex        ^((?!hostname|systemd_unit|message).)*$
        
            [FILTER]
              Name                aws
              Match               dataplane.*
              imds_version        v2
        
            [OUTPUT]
              Name                cloudwatch_logs
              Match               dataplane.*
              region              ${AWS_REGION}
              log_group_name      /aws/containerinsights/${CLUSTER_NAME}/dataplane
              log_stream_prefix   ${HOST_NAME}-
              auto_create_group   true
              extra_user_agent    container-insights
          host-log.conf: |
            [INPUT]
              Name                tail
              Tag                 host.dmesg
              Path                /var/log/dmesg
              Key                 message
              DB                  /var/fluent-bit/state/flb_dmesg.db
              Mem_Buf_Limit       5MB
              Skip_Long_Lines     On
              Refresh_Interval    10
              Read_from_Head      ${READ_FROM_HEAD}

            [INPUT]
              Name                tail
              Tag                 host.messages
              Path                /var/log/messages
              Parser              syslog
              DB                  /var/fluent-bit/state/flb_messages.db
              Mem_Buf_Limit       5MB
              Skip_Long_Lines     On
              Refresh_Interval    10
              Read_from_Head      ${READ_FROM_HEAD}

            [INPUT]
              Name                tail
              Tag                 host.secure
              Path                /var/log/secure
              Parser              syslog
              DB                  /var/fluent-bit/state/flb_secure.db
              Mem_Buf_Limit       5MB
              Skip_Long_Lines     On
              Refresh_Interval    10
              Read_from_Head      ${READ_FROM_HEAD}

            [FILTER]
              Name                aws
              Match               host.*
              imds_version        v2

            [OUTPUT]
              Name                cloudwatch_logs
              Match               host.*
              region              ${AWS_REGION}
              log_group_name      /aws/containerinsights/${CLUSTER_NAME}/host
              log_stream_prefix   ${HOST_NAME}.
              auto_create_group   true
              extra_user_agent    container-insights
      nodeSelector: {}
      resources:
        limits:
          cpu: 500m
          memory: 250Mi
        requests:
          cpu: 50m
          memory: 25Mi
  dcgmExporter:
    affinity:
      default:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-types
                operator: In
                values:
                - g3.4xlarge
                - g3.8xlarge
                - g3.16xlarge
                - g3s.xlarge
                - g4ad.2xlarge
                - g4ad.4xlarge
                - g4ad.8xlarge
                - g4ad.16xlarge
                - g4ad.xlarge
                - g4dn.2xlarge
                - g4dn.4xlarge
                - g4dn.8xlarge
                - g4dn.12xlarge
                - g4dn.16xlarge
                - g4dn.metal
                - g4dn.xlarge
                - g5.2xlarge
                - g5.4xlarge
                - g5.8xlarge
                - g5.12xlarge
                - g5.16xlarge
                - g5.24xlarge
                - g5.48xlarge
                - g5.xlarge
                - g5g.2xlarge
                - g5g.4xlarge
                - g5g.8xlarge
                - g5g.16xlarge
                - g5g.metal
                - g5g.xlarge
                - g6.2xlarge
                - g6.4xlarge
                - g6.8xlarge
                - g6.12xlarge
                - g6.16xlarge
                - g6.24xlarge
                - g6.48xlarge
                - g6.xlarge
                - g6e.2xlarge
                - g6e.4xlarge
                - g6e.8xlarge
                - g6e.12xlarge
                - g6e.16xlarge
                - g6e.24xlarge
                - g6e.48xlarge
                - g6e.xlarge
                - gr6.4xlarge
                - gr6.8xlarge
                - p2.8xlarge
                - p2.16xlarge
                - p2.xlarge
                - p3.2xlarge
                - p3.8xlarge
                - p3.16xlarge
                - p3dn.24xlarge
                - p4d.24xlarge
                - p4de.24xlarge
                - p5.48xlarge
                - p5e.48xlarge
                - p5en.48xlarge
                - ml.g3.4xlarge
                - ml.g3.8xlarge
                - ml.g3.16xlarge
                - ml.g3s.xlarge
                - ml.g4ad.2xlarge
                - ml.g4ad.4xlarge
                - ml.g4ad.8xlarge
                - ml.g4ad.16xlarge
                - ml.g4ad.xlarge
                - ml.g4dn.2xlarge
                - ml.g4dn.4xlarge
                - ml.g4dn.8xlarge
                - ml.g4dn.12xlarge
                - ml.g4dn.16xlarge
                - ml.g4dn.metal
                - ml.g4dn.xlarge
                - ml.g5.2xlarge
                - ml.g5.4xlarge
                - ml.g5.8xlarge
                - ml.g5.12xlarge
                - ml.g5.16xlarge
                - ml.g5.24xlarge
                - ml.g5.48xlarge
                - ml.g5.xlarge
                - ml.g5g.2xlarge
                - ml.g5g.4xlarge
                - ml.g5g.8xlarge
                - ml.g5g.16xlarge
                - ml.g5g.metal
                - ml.g5g.xlarge
                - ml.g6.2xlarge
                - ml.g6.4xlarge
                - ml.g6.8xlarge
                - ml.g6.12xlarge
                - ml.g6.16xlarge
                - ml.g6.24xlarge
                - ml.g6.48xlarge
                - ml.g6.xlarge
                - ml.g6e.2xlarge
                - ml.g6e.4xlarge
                - ml.g6e.8xlarge
                - ml.g6e.12xlarge
                - ml.g6e.16xlarge
                - ml.g6e.24xlarge
                - ml.g6e.48xlarge
                - ml.g6e.xlarge
                - ml.gr6.4xlarge
                - ml.gr6.8xlarge
                - ml.p2.8xlarge
                - ml.p2.16xlarge
                - ml.p2.xlarge
                - ml.p3.2xlarge
                - ml.p3.8xlarge
                - ml.p3.16xlarge
                - ml.p3dn.24xlarge
                - ml.p4d.24xlarge
                - ml.p4de.24xlarge
                - ml.p5.48xlarge
                - ml.p5e.48xlarge
                - ml.p5en.48xlarge
    nodeSelector: {}
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 250m
        memory: 128Mi
      tolerations: {}
